#ifndef ZY_COLLISION_MANAGER_CONFIG_H
#define ZY_COLLISION_MANAGER_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef BUILD_ZY_COLLISIONMANAGER
#  define ZY_COLLISIONMANAGER_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define ZY_COLLISIONMANAGER_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif //ZY_COLLISION_MANAGER_CONFIG_H
