#ifndef ZY_PIPELINE_TASKS_CONFIG_H
#define ZY_PIPELINE_TASKS_CONFIG_H

#include <sofa/helper/system/config.h>

#ifdef BUILD_ZY_PIPELINE_TASKS
#  define ZY_PIPELINE_TASKS_API SOFA_EXPORT_DYNAMIC_LIBRARY
#else
#  define ZY_PIPELINE_TASKS_API SOFA_IMPORT_DYNAMIC_LIBRARY
#endif

#endif //ZY_PIPELINE_TASKS_CONFIG_H
